### ISSUE TITLE
Docs refer to files that are in a private repo

### ISSUE THREAD

**Issue by tomwimmenhove** [metrico/iox-community#6]
The readme still contains things like:

```Sh
wget -qO- "https://github.com/influxdata/influxdb_iox/raw/main/test_fixtures/lineproto/metrics.lp" | \
curl -v "http://127.0.0.1:8080/api/v2/write?org=company&bucket=sensors" --data-binary @-
```

Where, https://github.com/influxdata/influxdb_iox/raw/main/test_fixtures/lineproto/metrics.lp returns 404. There's no way for people new to IOX to easily start experimenting.

**Comment by tomwimmenhove** [comment]
Ah, it's still available in another repo: https://raw.githubusercontent.com/metrico/influxdb_iox/main/test_fixtures/lineproto/metrics.lp

**Comment by lmangani** [comment]
> There's no way for people new to IOX to easily start experimenting.

@tomwimmenhove thanks for the report! InfluxData has moved the repository to private mode, breaking any link.

We're actually trying to make the fun possible here 👍

**Comment by lmangani** [comment]
Fixed! Consider a PR next time to join the fun 😉
