### ISSUE TITLE
iox-gc container fails to start - missing influxdb_iox binary

### ISSUE THREAD

**Issue by mugen6** [metrico/iox-community#7]
Thanks for putting this together - InfluxDB 3.0 is looking very promising.

I started with a fresh VM with docker and did the following:

git clone https://github.com/metrico/iox-community.git
docker pull ghcr.io/metrico/influxdb-edge-musl:latest
docker-compose up -d

Got the following errors:

```
WARNING: The INFLUXDB_TOKEN variable is not set. Defaulting to a blank string.
Creating iox    ... done
Creating iox-gc                  ... error
Creating iox-community_grafana_1 ... 
Creating nginx_container         ... 

Creating iox-community_grafana_1 ... done
Creating nginx_container         ... done

ERROR: for iox-gc  Cannot start service iox-gc: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/influxdb_iox": stat /influxdb_iox: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

The containers that did come up look like this:

```
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS          PORTS                                                                                                           NAMES
5e90c5097ece   nginx:latest                                "/docker-entrypoint.…"   25 seconds ago   Up 23 seconds   80/tcp, 0.0.0.0:8086->8086/tcp, :::8086->8086/tcp                                                               nginx_container
2232eb83346e   grafana/grafana:latest                      "/run.sh"                25 seconds ago   Up 23 seconds   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                       iox-community_grafana_1
3adcd9edd241   ghcr.io/metrico/influxdb-edge-musl:latest   "/influxdb_iox run g…"   26 seconds ago   Created         8080/tcp, 8082/tcp                                                                                              iox-gc
aacf9434d5bc   ghcr.io/metrico/influxdb-edge-musl:latest   "/influxdb3 serve"       26 seconds ago   Up 24 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 8081/tcp, 0.0.0.0:8082->8082/tcp, :::8082->8082/tcp, 8083-8084/tcp   iox
```

I also get this:
```
$ curl http://127.0.0.1:8086/health
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.25.4</center>
</body>
</html>
```

Do I have to change something in the docker-compose.yml?

**Comment by lmangani** [comment]
Hello @mugen6 sadly the folks at influx keep making changes and chopping features off iox (compared to its initial form, as you can see from the binary loosing significant size from iox to influxdb3) and the original instructions and settings are no longer producing the expected results. I'm not sure what the future holds for InfluxDB3 but at the moment its no longer seems to be the IOx we were invested into and it became some sort of "opencore" minimal version lacking major features.

You can see we still provide the older [full featured build](https://github.com/metrico/iox-community/releases/tag/main)
The `influxdb_iox` build will work with the documented settings, while the current `influxdb3` build is affected by changes.

**Comment by mugen6** [comment]
Hi @lmangani, thanks for such a quick response.

That is a shame to hear, because after evaluating several time series DBs, Influx 3.0 looked to tick all the right boxes. What other DBs are you looking at, if you were to abandon Influx?

So I can run the influx_iox binary but if I wanted to get this working in Docker, do I just rebuild the docker image with the old binary?

**Comment by lmangani** [comment]
I share the sentiment and still have hope for it to be fully opensourced again. This is the "old" full featured iox container: https://github.com/metrico/iox-community/pkgs/container/iox-musl

**Comment by mugen6** [comment]
Thanks for your efforts, but I switched to QuestDB instead.
